# FILE: internal/templates/php_laravel/Dockerfile.tmpl

# The PHP version is now a dynamic variable from our detector
ARG PHP_VERSION={{ .LanguageVersion }}

# --- Build Stage ---
FROM composer:2-php${PHP_VERSION} AS vendor
WORKDIR /app
COPY . .
RUN composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

# --- Final Stage ---
FROM php:${PHP_VERSION}-fpm-alpine
WORKDIR /var/www/html

# Install required PHP extensions
RUN apk add --no-cache oniguruma-dev libxml2-dev
RUN docker-php-ext-install mbstring dom pdo pdo_mysql

# Copy application files
COPY . .
# Copy installed vendor dependencies from the build stage
COPY --from=vendor /app/vendor/ /var/www/html/vendor/

# Set correct permissions
RUN chown -R www-data:www-data /var/www/html

# Expose port for PHP-FPM
EXPOSE 9000
CMD ["php-fpm"]